# Site settings
title: Namilabs
email: hello@namilabs.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://namilabs.com" # the base hostname & protocol for your site

twitter_username: namilabscom
github_username: namilabs

# Build settings
markdown: kramdown
